chajarat/chajarat/urls.py
from django.urls import path
from django.urls import include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView
import os,sys


currentdir = os.path.dirname(os.path.realpath(__file__))
parentdir = os.path.dirname(currentdir)

urlpatterns = [
     path('admin/', admin.site.urls),
     path('chajarat/',include('map.urls')),
     path('', RedirectView.as_view(url='chajarat/', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chajarat/map/urls.py
from django.views.generic import TemplateView
from django.conf.urls import url
from djgeojson.views import GeoJSONLayerView
from .models import Project
from . import views
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path

urlpatterns = [
     url(r'^$', TemplateView.as_view(template_name='index.html'), name='map'),
     url(r'^data$', GeoJSONLayerView.as_view(model=Project, properties=('title', 'description', 'picture_url','url','website')), name='data'),
     path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
     path('projects/', views.departementListView, name='projects'),
     path('departement/<int:pk>', views.departementDetailView, name='departement'),

]

chajarat/map/models.py
from djgeojson.fields import PointField
from django.db import models
import re


class Project(models.Model):

    title = models.CharField(max_length=200)
    description = models.TextField()
    picture_url = models.URLField(max_length=200)
    url = models.URLField(max_length=200)
    geom = PointField()
    city = models.CharField(max_length=50)
    departement = models.ForeignKey('Departement',on_delete=models.CASCADE)
    nbArbres = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.title

    # Metadata
    class Meta:
        ordering = ['title']

    @property
    def website(self):
        outer = re.compile(r"(.*)my-tree(.*)")
        m = outer.search(self.url)
        if (m != None):
            return "my-tree"
        outer = re.compile(r"(.*)atreeforyou(.*)")
        m = outer.search(self.url)
        if (m != None):
            return "atreeforyou"
        outer = re.compile(r"(.*)plantonspourlavenir(.*)")
        m = outer.search(self.url)
        if (m != None):
            return "plantonspourlavenir"
        return "Null"


class Departement(models.Model):
    nb = models.PositiveIntegerField(default=0)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

chajarat/map/views.py
from django.shortcuts import render

from django.shortcuts import render

from map.models import Project
from map.models import Departement
from django.db.models import Sum
from django.views import generic

import csv
import os, sys
currentdir = os.path.dirname(os.path.realpath(__file__))
parentdir = os.path.dirname(currentdir)
sys.path.append(parentdir)

def map(request):
    labels = []
    data = []

    queryset = Project.objects.values('departement').annotate(Sum('nbArbres'))[:10]
    for pj in queryset:
        labels.append(Departement.objects.get(id=pj['departement']).name)
        data.append(pj['nbArbres__sum'])

    return render(request, 'index.html', {
        'labels': labels,
        'data': data,
    })


def departementListView(request):
    template_name = 'project_list.html'
    # Read all departements
    departements = []

    filedir = parentdir + '/scraping'
    with open(filedir+'/departement.csv') as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        line_count = 0
        for row in csv_reader :
            if row == []:
                break
            if line_count == 0:
                line_count += 1
            else:
                line_count += 1
                departements += [{ 'departement': row[1], 'nb' : int(row[0]) }]
    return render(request, template_name, context={'departements': departements})


def departementDetailView(request,pk):
    departements = Departement.objects.all()
    template_name = 'departement_detail.html'
    projects = Project.objects.filter(departement__nb=pk)
    nb_trees_planted = projects.aggregate(Sum('nbArbres'))['nbArbres__sum']
    nb_projects = projects.count()
    return render(request, template_name, context={'project_list': projects, 'nb_trees_planted':nb_trees_planted,'nb_projects':nb_projects})

chajarat/map/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load leaflet_tags %}
  {% load static %}
  {% leaflet_js %}
  {% leaflet_css %}
  <link rel="shortcut icon"  href="{% static 'favicon.ico' %}"/>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;1,300;1,400&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
  <link rel="stylesheet" href="{% static 'css/album.css' %}">
  <link rel="stylesheet" href="{% static 'css/departement_list.css'%}">
</head>



<body>
  {% block carousel %}
  {% endblock %}

  <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:25%;">
    <h3 class="w3-bar-item">Menu</h3>
    {% block menu %}
    <a href="{% url 'map' %}" class="w3-bar-item w3-button">Carte des Projets</a>
    <a href="{% url 'projects' %}" class="w3-bar-item w3-button">Liste des Projets</a>
    {% endblock %}
  </div>

  <div class="inner">
    <h1>
      {% block h1 %}
      {% endblock %}
    </h1>
    <div class="col-sm-2">
      {% block sidebar %}
     {% endblock %}
      </div>
<!-- Page Content -->
    <div class="col-sm-10">
      {% block content %}
      {% endblock %}
    </div>
  </div>
</body>
</html>

chajarat/map/templates/departement_detail.html
{% extends "base.html" %}

{% block h1 %}
Projets dans ton département
{% endblock %}

{% block content %}



      {% for project in project_list %}
        <div class="row">
            <div class="card">
            <img src={{project.picture_url}} width="100%" height="100%"/>
              <div class="card-body">
                <p class="card-text"> {{ project.title }} </p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <form action={{project.url}}>
                    <button type="submit" class="btn btn-sm btn-outline-secondary"> >> En savoir +</button>
                    </form>
                   </div>
                  <small class="text-muted"> {{ project.nbArbres }} arbre plantés !</small>
                </div>
              </div>
            </div>
          </div>
       {% endfor %}


      </div>
    </div>


</main>



{% endblock %}

chajarat/map/templates/index.html
{% extends 'base.html' %}
{% load leaflet_tags %}

<title>Chajarat|Carte</title>

{% block h1 %}
Carte des Projets
{% endblock %}

{% block carousel %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="carousel-caption top" >
      <img src='../static/css/chajarat.png' alt="Chajarat-logo">
      <h2>Chajarat</h2>
    </div>
    <div class="item active">
      <img src='../static/css/forest1.jpeg' alt="Forest">
      <div class="carousel-caption">
        <h4 style = "color:white;">Découvrez les projets de reforestation en France </h4>
        <p>Contrairement à ce que vous pouvez penser, plein de projets de reboisement existent en France!</p>
      </div>
    </div>

  <div class="item">
    <img src="../static/css/forest2.jpeg" alt="Planting">
    <div class="carousel-caption">
      <h4 style = "color:white;">Aidez les associations à accomplir leurs missions</h4>
      <p>Plein d'associations sont actives à côté de chez vous</p>
    </div>
  </div>

  <div class="item">
    <img src="../static/css/forest3.jpeg" alt="Book">
    <div class="carousel-caption">
      <h4 style = "color:white;"> Connaissez vous les projets de votre région ? </h4>
      <p>Informez vous sur les projets de votre Région</p>
    </div>
  </div>
</div>

<!-- Left and right controls -->
<a class="left carousel-control" href="#myCarousel" data-slide="prev">
  <span class="glyphicon glyphicon-chevron-left"></span>
  <span class="sr-only">Previous</span>
</a>
<a class="right carousel-control" href="#myCarousel" data-slide="next">
  <span class="glyphicon glyphicon-chevron-right"></span>
  <span class="sr-only">Next</span>
</a>
</div>
{% endblock %}



{% block content %}
<script>
  function bindPopups(feature, layer) {
    var props = feature.properties;
    var content =`<div class="popup">\
        <h7><a href = ${props.url}>${props.title}</a></h7>\
        <a href = ${props.url}><img src="${props.picture_url}"/></a>\
        <p>${props.description}</p>\
        </div>`;
    layer.bindPopup(content);
  }

  var dataurl = '{% url "data" %}'
  window.addEventListener("map:init", function (event) {
  var map = event.detail.map;



  //show markers on zoom



  // follow popup on click
  map.on('popupopen', function(e) {
    var px = map.project(e.target._popup._latlng); // find the pixel location on the map where the popup anchor is
    px.y -= e.target._popup._container.clientHeight/2; // find the height of the popup container, divide by 2, subtract from the Y axis of marker location
    map.panTo(map.unproject(px),{animate: true}); // pan to new center
  });


  // Launch map: Download GeoJSON data with Ajax
  fetch(dataurl)
    .then(function(resp) {
      return resp.json();
    })
    .then(function(data) {
      L.geoJson(data, {onEachFeature: bindPopups}).addTo(map);
    });
  });
</script>
{% leaflet_map "main" %}
{% endblock %}

chajarat/map/templates/project_list.html
{% extends "base.html" %}
{% block h1 %}
Choisis ton departement
{% endblock %}


{% block content %}
<ul class="list_departement">
    {% for departement in departements %}
      <li>
        <a href="{% url 'departement' departement.nb %}">{{departement.departement}}
      </li>
    {% endfor %}
  </ul>
{% endblock %}